##
alias l='ls'
alias ll='ls -l'
alias sl='ls'
alias catp='pygmentize -g'
alias cd..='cd ..'
alias d='cd'
alias ..='cd ..'
alias nf='neofetch'
alias nfl='neofetch | lolcat'
alias duh='du -ha --max-depth=1 . | sort -h'
alias dum='du -ma --max-depth=1 . | sort -n'
alias fh='echo && free -h && echo && df -h && echo'
alias tls='tmux ls'
alias tns='tmux new -s'
alias ta='tmux attach -t'
alias k='kubectl'
alias klns='kubectl get namespaces'
alias kgns='echo "$(kubectl config view --minify --output 'jsonpath={..namespace}')"'
alias kans='kubectl config set-context --current --namespace'
